### ISSUE TITLE
Don't work on s22 ultra

### ISSUE THREAD

**Issue by Angeloxdd** [preparetodietm/ml_unlocker#1]
Failed to unlock fps 
![Screenshot_20220714-183446_Termux](https://user-images.githubusercontent.com/95893977/179033221-888193b2-a921-418f-889b-47f3caba3cc6.jpg)

**Comment by preparetodietm** [comment]
Check your device fps by running this code in terminal

`su -c cat /sys/devices/virtual/graphics/fb0/dynamic_fps`

then send the result here 😊

**Comment by KaIZeR99-code** [comment]
Same for me. Then, no directory found when I write above command.
![Screenshot_20221103-113419_Terminal_Emulator](https://user-images.githubusercontent.com/83866575/199643026-6753266a-c24e-4922-8fc9-1ffbf82e10af.png)

**Comment by ZenBunZakuro** [comment]
cat /sys/devices/virtual/graphics/fb0/dynamic_fps      <
/system/bin/sh: -c: inaccessible or not found
127|:/data/data/com.termux/files/home #

**Comment by preparetodietm** [comment]
thanks, I will try to fix it on the next version 😊.
