### ISSUE TITLE
OnePlus 8 not work

### ISSUE THREAD

**Issue by ZenBunZakuro** [preparetodietm/ml_unlocker#2]
![Screenshot_20221115-115107_Termux](https://user-images.githubusercontent.com/49030662/201836942-e6056924-32cd-4d2c-964a-d65d73b0fcb0.png)

**Comment by ZenBunZakuro** [comment]
cat /sys/devices/virtual/graphics/fb0/dynamic_fps <
/system/bin/sh: -c: inaccessible or not found

**Comment by AvishekPD** [comment]
> cat /sys/devices/virtual/graphics/fb0/dynamic_fps < /system/bin/sh: -c: inaccessible or not found

got any alternative for this?

**Comment by preparetodietm** [comment]
Fixed on the next version 😊
