### ISSUE TITLE
Not working on my Redmi Note 10 Pro

### ISSUE THREAD

**Issue by parthibratan** [preparetodietm/ml_unlocker#3]
![Screenshot_2023-01-05-12-58-36-434_com termux](https://user-images.githubusercontent.com/122037373/210816095-5b79775c-a9a1-4539-9f61-cf9eb77ab2e1.jpg)
Am I doing something wrong here?

**Comment by preparetodietm** [comment]
It's the script problem. I will fix it and wait for the mext version 😊.
